dependencies:
  aht20:
    url: github.com/davidlao2k/aht20-driver
    version: ^1.0.0
  bmp280:
    url: github.com/harshkc03/bmp280-driver
    version: ^1.0.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.8.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.1.0
