dependencies:
  aht20:
    url: github.com/davidlao2k/aht20-driver
    version: ^1.0.0
  bmp280:
    url: github.com/harshkc03/bmp280-driver
    version: ^1.0.0
  certificate-roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.11.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.9.0
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.13.1
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.1.0
  watchdog:
    url: github.com/toitware/toit-watchdog
    version: ^1.4.1
